### ISSUE TITLE
Given final block not properly padded

### ISSUE THREAD

**Issue by mridah** [blocktrail/cryptojs-aes-php#1]
It gives me encrypted strings like
    `U2FsdGVkX18t7m4RKL0DRM46yjp1gmddZFhFQNBugF2uDvR0sD6txedKmmbpTKMp2+4JODOuHqSMJgDwPJ0xNA==`

But I can't decrypt it. Even when using services like [https://www.devglan.com/online-tools/aes-encryption-decryption](https://www.devglan.com/online-tools/aes-encryption-decryption), it gives the following error:

> Given final block not properly padded. Such issues can arise if a bad key is used during decryption.

How to resolve this ? how can i get a base64 encoded string ?  @rubensayshi  @afk11  @boazeb

**Comment by afk11** [comment]
Under the hood this operation uses openssl which uses it's own serialization format for ciphertexts. To decrypt without using openssl you'll need to implement the KDF (which you can get from this library) to get the key and IV, and then decode the rest of the string to get the ciphertext payload.

FYI - this package was only written to be compatible with openssl and it's very weak defaults (md5, basically no iterations). You should use something like https://github.com/defuse/php-encryption unless you have a specific reason to use this algo - we have deprecated its use in our projects.
